---
- hosts: all
  remote_user: root
  vars:
    - app_location: "/var/app"
  tasks:
    - ping:

    - command: bash -c "curl -sSL https://get.docker.com/ubuntu/ | sudo sh" creates=/usr/bin/docker
    - command: bash -c "curl https://bootstrap.pypa.io/get-pip.py | python" creates=/usr/local/bin/pip

    - apt: name=nginx
    - copy: src=nginx.conf dest=/etc/nginx/sites-enabled
    - service: name=nginx enabled=yes state=reloaded

    - pip: name=docker-py
    - service: name=docker enabled=yes state=running

    - file: path={{app_location}} state=absent
    - copy: src=../release/ dest={{app_location}}

    - docker_image: path={{app_location}} name={{docker_name}} state=build
    - docker: image={{docker_name}} name={{docker_name}}-1 state=absent
    - docker: image={{docker_name}} name={{docker_name}}-1 ports={{docker_port}}:3000 state=present
